### PR TITLE
RELATED: RAIL-551 ChartTransformation and TableTransformation support empty result and optional executionResult.headers

### PR DESCRIPTION
**Pull request by tomasreichmann**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/275/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/167/ : FAILURE in 28s

**Comment by tomasreichmann** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/276/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/168/ : FAILURE in 3m 18s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/274/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/889/ : SUCCESS in 2m 49s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/157/ : ABORTED in 1h 00m 00s (non-voting)

**Pull request closed without merging**
