### PR TITLE
RELATED: BB-497 added several s-* classnames for testing purposes

### PR DESCRIPTION
**Pull request by strouhaljan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/643/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/420/ : SUCCESS in 52s

**Comment by strouhaljan** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-indigo-visualizations-storybook-zuul-docker/148/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/644/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/305/ : SUCCESS in 3m 41s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-merge-compliance-check/116/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/421/ : SUCCESS in 47s

**Pull request merged**
