### PR TITLE
RELATED: RAIL-560 Expose chart.reflow() from SDK components

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/341/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/931/ : FAILURE in 2m 23s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/199/ : FAILURE in 2m 26s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/342/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/932/ : SUCCESS in 2m 36s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/200/ : SUCCESS in 1m 51s (non-voting)

**Comment by zbycz** [comment]
`@gooddata/indigo-visualizations@1.1.0-pavelzgdc-pzb-560-resize-2017-12-18T15-54-42-744Z`

**Comment by zbycz** [comment]
Wont fix. Encourage solution via window.resize event: https://github.com/gooddata/gooddata-js-boilerplate/pull/18

**Pull request closed without merging**
