### PR TITLE
RELATED: RAIL-255 Update @gooddata/test-storybook

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by zbycz** [comment]
extended test - storybook

**Comment by langhammerp** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-indigo-visualizations-storybook-zuul-docker/27/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/300/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/180/ : SUCCESS in 5m 33s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-merge-compliance-check/84/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/903/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/171/ : ABORTED in 1h 00m 01s (non-voting)

**Pull request merged**
