### PR TITLE
RELATED: RAIL-298 Vis. library works with new AFM

### PR DESCRIPTION
**Pull request by ocetnik**
@gooddata/indigo-visualizations@0.16.0-tomasreichmann-ocetnik-doc-tre-new-afm-2017-11-27T13-33-30-381Z

### CODE REVIEW

**Comment by ocetnik** [comment]
extended test - gemini

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/223/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/857/ : FAILURE in 2m 13s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/121/ : ABORTED in 1h 00m 00s (non-voting)

**Comment by langhammerp** [comment]
extended test - gemini

**Comment by osklive-kacatko** [comment]
Link to Gemini test result:

https://ci.intgdc.com/job/gooddata-indigo-visualizations-gemini-zuul/160/artifact/gemini/reports/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/225/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/150/ : SUCCESS in 8m 49s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/224/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/858/ : SUCCESS in 2m 37s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/122/ : ABORTED in 1h 00m 00s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-merge-compliance-check/81/ : SUCCESS in 47s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/863/ : SUCCESS in 14m 45s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/127/ : SUCCESS in 3m 24s (non-voting)

**Pull request merged**
