### PR TITLE
RELATED: RAIL-255 Add workaround for @storybook/react@3.2.0 custom webpack config

### PR DESCRIPTION
**Pull request by ocetnik**

### CODE REVIEW

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/279/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/892/ : SUCCESS in 3m 00s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/160/ : SUCCESS in 2m 42s (non-voting)

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-indigo-visualizations-storybook-zuul-docker/17/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/280/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/170/ : SUCCESS in 5m 13s

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/281/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/893/ : SUCCESS in 2m 10s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/161/ : SUCCESS in 2m 29s (non-voting)

**Comment by ocetnik** [comment]
extended test - storybook

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/283/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/894/ : SUCCESS in 3m 42s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/162/ : SUCCESS in 1m 28s (non-voting)

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-indigo-visualizations-storybook-zuul-docker/19/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/284/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/172/ : SUCCESS in 4m 08s

**Pull request merged**
