### PR TITLE
RELATED: BB-510 Add MSIE NodeList.forEach polyfill

### PR DESCRIPTION
**Pull request by petrjanu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/345/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/935/ : FAILURE in 1m 37s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/203/ : FAILURE in 2m 00s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/347/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/937/ : SUCCESS in 2m 24s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/205/ : SUCCESS in 2m 46s (non-voting)

**Comment by petrjanu** [comment]
extended test - storybook

**Comment by osklive-kacatko** [comment]
Link to Storybook test result:

https://ci.intgdc.com/job/gooddata-indigo-visualizations-storybook-zuul-docker/42/artifact/test-storybook/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-opensource-repository-check/348/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-pull-request-dispatcher/196/ : SUCCESS in 5m 38s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-indigo-visualizations-merge-compliance-check/87/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-el7/938/ : SUCCESS in 2m 22s
- https://ci.intgdc.com/job/gooddata-indigo-visualizations-unit-tests-zuul-docker-el7/206/ : SUCCESS in 1m 32s (non-voting)

**Pull request merged**
